{% set version = "0.1.30" %}
{% set name = "PyScreeze" %}

package:
  name: pyscreeze
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyScreeze-{{ version }}.tar.gz
  sha256: 74098ad048e76a6231dcfa6243343af94459b8c829f9ccb7a44a5d3b147a67d1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - pillow >=9.2.0
    - pyscreenshot

test:
# Remove test suite for now because it requires screengrabs etc.
#   source_files:
#     - tests
  imports:
    - pyscreeze
  commands:
    - pip check
#     - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
#     - pytest

about:
  home: https://github.com/asweigart/pyscreeze
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A simple, cross-platform screenshot module for Python 2 and 3.

extra:
  recipe-maintainers:
    - thewchan
    - jschueller
