{% set version = "0.1.29" %}
{% set name = "PyScreeze" %}

package:
  name: pyscreeze
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyScreeze-{{ version }}.tar.gz
  sha256: d074547795e128da176599a6d4470500e425d49b05cf22e9808a7984c3612836

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - pillow >=9.2.0
    - pyscreenshot

test:
  source_files:
    - tests
  imports:
    - pyscreeze
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/asweigart/pyscreeze
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A simple, cross-platform screenshot module for Python 2 and 3.

extra:
  recipe-maintainers:
    - thewchan
    - jschueller
