{% set version = "0.1.18" %}
{% set name = "PyScreeze" %}

package:
  name: pyscreeze
  version: {{ version }}

source:
  fn: PyScreeze-{{ version }}.tar.gz
  sha256: 11737e196a5dc35b723e0b34784559c052c10af8518f37e9cf70c86b5936fb00
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pillow

test:
  imports:
    - pyscreeze

about:
  home: https://github.com/asweigart/pyscreeze
  license: BSD 3-Clause
  license_family: BSD
  # https://github.com/asweigart/pyscreeze/pull/31
  #license_file: LICENSE.txt
  summary: A simple, cross-platform screenshot module for Python 2 and 3.

extra:
  recipe-maintainers:
    - jschueller
